"""
reports.py
 
Reports page — Phase 3 (final UI refinement, pre-backend-integration
polish). Historical review, report generation, and export surface for
BMERMS.
 
Answers: "What happened during this operation, and how can commanders
review or export it?" — NOT "what is happening right now?" (that's
Dashboard/Analytics). Accordingly this page deliberately does NOT
duplicate:
    Dashboard  -> live operational snapshot
    Simulation -> real-time control
    Facilities -> per-facility console
    Patients   -> casualty registry / live case management
    Resources  -> live fleet inventory
    Analytics  -> live trend / forecast / AI decision support
 
PHASE 3 CHANGES (this file only — UI polish, no backend, no other page)
    1. constants.BATTLE_SECTORS is imported defensively: if it's ever
       removed from constants.py, REPORT_SECTORS falls back to a local
       Alpha-Delta list instead of raising ImportError at import time.
    2. Mock "generated by" values are now role codes (OPS-OFFICER,
       MED-COMMAND, DUTY-OFFICER, SYSTEM) instead of invented named
       officers, since no personnel/identity table exists yet.
    3. Every mock report now carries a report_id (RPT-0xx).
    4. Every report row shows a bracketed tactical type tag ([CAS],
       [FAC], [RES], [INC], [TRT], [SIT]) reusing the same
       TEMPLATE_BADGE mapping Report Templates uses.
    5. Report Metadata strip: "Filters Applied" moved to its own
       full-width row with explicit word-wrap styling, so long filter
       strings wrap cleanly instead of overflowing or breaking mid-word
       inside a narrow column.
    6. "Export Queue" renamed to "Queued Reports" everywhere (tab, KPI
       card, data function, stats strip).
    7. All three report tabs (Recent / Queued / Archived) now show a
       distinct, styled empty state instead of a bare caption.
    8. A compact report-statistics strip (Completed / Queued / Archived
       / Failed counts) sits above the report tabs.
    9. Report Preview shows a professional placeholder message until a
       template or the builder has generated at least one report in this
       session; only then do the metadata strip + Summary/Tables/Charts
       tabs appear.
    10. A small classification badge ("CLASSIFICATION: OPERATIONAL USE")
        sits at the top of the page, reusing the existing
        .medevac-status-badge class already defined in theme.css (no CSS
        file touched).
 
BACKEND STATUS (unchanged)
    No Reports table exists in the schema yet (see constants.py /
    models.py — there is no Report/ReportTemplate dataclass today), and
    the backend currently only supports CSV export, not report generation
    or persistence. Every data function below therefore returns
    placeholder data shaped like its eventual real source, with a
    "TODO Integration" docstring naming the future crud.py function (or
    schema addition) that will replace it. No function here reads or
    writes the SQLite database — this file has zero backend wiring.
 
    Report IDs, role-code attribution, and status counts are all
    UI-only/mock for now — none of them read a real identity, job-queue,
    or persistence layer, none of which exist backend-side yet either.
 
Explicitly out of scope (per spec) even as placeholders: PDF export,
Excel export, email delivery, AI-generated narrative summaries. Only CSV
export placeholders appear, matching current backend capability.
"""
 
from __future__ import annotations
 
from datetime import date, datetime, timedelta
 
import plotly.graph_objects as go
import streamlit as st
 
from components.metric_card import metric_card
from components.panel import panel
from components.buttons import primary_button, secondary_button
from utils.theme import COLOR_PRIMARY, COLOR_DANGER, COLOR_WARNING, COLOR_INFO, COLOR_TEXT_SECONDARY
from data.reports_mock_data import (
    FACILITY_ORDER,
    SEVERITY_LIST,
    INCIDENT_TYPES,
    CASUALTY_STATUSES,
    REPORT_SECTORS,
) 
 
# --------------------------------------------------------------------------
# CONSTANTS
# --------------------------------------------------------------------------
 
CHART_HEIGHT_PX = 260
HISTORY_DAYS = 7
 
_ACCENT = {
    "primary": COLOR_PRIMARY,
    "warning": COLOR_WARNING,
    "danger": COLOR_DANGER,
    "info": COLOR_INFO,
}
 
SEVERITY_COLOR = {
    "Critical": COLOR_DANGER,
    "Serious": "#E07B26",
    "Moderate": COLOR_WARNING,
    "Mild": COLOR_PRIMARY,
}
 
REPORT_STATUS_COLOR = {
    "Completed": "primary",
    "Processing": "warning",
    "Queued": "warning",
    "Pending": "warning",
    "Failed": "danger",
    "Archived": "info",
}
 
# Tactical letter-badge per template — used both on Report Templates cards
# and as the bracketed [XXX] type tag on every report list row.
TEMPLATE_BADGE = {
    "Casualty Summary": "CAS",
    "Facility Performance": "FAC",
    "Resource Utilization": "RES",
    "Incident Timeline": "INC",
    "Treatment Outcomes": "TRT",
    "Mission SITREP": "SIT",
}
 
TEMPLATE_BADGE_COLOR = {
    "Casualty Summary": COLOR_DANGER,
    "Facility Performance": COLOR_INFO,
    "Resource Utilization": COLOR_PRIMARY,
    "Incident Timeline": COLOR_WARNING,
    "Treatment Outcomes": COLOR_INFO,
    "Mission SITREP": COLOR_PRIMARY,
}
 
# Role codes stand in for a future auth/session-identity system (none
# exists yet). Deliberately roles, not invented named officers.
ROLE_OPS_OFFICER = "OPS-OFFICER"
ROLE_MED_COMMAND = "MED-COMMAND"
ROLE_DUTY_OFFICER = "DUTY-OFFICER"
ROLE_SYSTEM = "SYSTEM"
 
# Mock "current operator" for reports generated interactively in this
# session (Report Builder / template Generate buttons).
_MOCK_CURRENT_USER = ROLE_DUTY_OFFICER
 
 
# --------------------------------------------------------------------------
# DATA LAYER
# Placeholder data only. Every function is shaped to match its eventual
# real source so backend wiring later replaces function bodies, not
# callers/UI. Nothing here touches sqlite3 or database/db.py.
# --------------------------------------------------------------------------
 
def _get_report_kpis() -> list[dict]:
    """
    # TODO Integration:
    # Source -> a new crud.get_report_summary_stats() once the Reports
    # table exists (report_id, report_name, report_type, generated_time,
    # status, requested_by, file_path). Until that schema lands, these
    # are static placeholders, not derived from any live table.
    """
    return [
        {"title": "Reports Generated Today", "value": 6, "color": "primary"},
        {"title": "Available Templates", "value": 6, "color": "info"},
        {"title": "Last Generated Report", "value": "09:42", "color": "info"},
        {"title": "Queued Reports", "value": 2, "color": "warning"},
        {"title": "Archived Reports", "value": 148, "color": "primary"},
    ]
 
 
def _get_report_templates() -> list[dict]:
    """
    # TODO Integration:
    # Template list itself can stay code-defined (it's a fixed catalog,
    # not data), but "last generated"/"available" per template will read
    # from the same future Reports table as _get_report_kpis(). Badge
    # codes (TEMPLATE_BADGE) are presentation-only and never touch the
    # backend.
    """
    return [
        {
            "name": "Casualty Summary",
            "description": "Casualty counts by severity, sector, and status over a date range.",
        },
        {
            "name": "Facility Performance",
            "description": "Occupancy, throughput, and queue trends per treatment facility.",
        },
        {
            "name": "Resource Utilization",
            "description": "Ambulance, helicopter, and medical team usage over time.",
        },
        {
            "name": "Incident Timeline",
            "description": "Chronological incident log with type, sector, and casualty count.",
        },
        {
            "name": "Treatment Outcomes",
            "description": "Treatment durations and outcome status by facility and severity.",
        },
        {
            "name": "Mission SITREP",
            "description": "Consolidated situation report across all sections above.",
        },
    ]
 
 
def _get_filter_options() -> dict:
    """
    # TODO Integration:
    # facilities/severities/incident_types/statuses/sectors already mirror
    # constants.py 1:1 (no invented values; REPORT_SECTORS falls back
    # locally only if constants.BATTLE_SECTORS is ever removed — see top
    # of file). operations is the one list here without a constants.py
    # source — replace with crud.get_operations()
    # (Operation.operation_name) once wired; it's a placeholder list only
    # until then.
    """
    return {
        "facilities": ["All"] + FACILITY_ORDER,
        "severities": ["All"] + SEVERITY_LIST,
        "incident_types": ["All"] + INCIDENT_TYPES,
        "operations": ["All", "Operation Shield Wall", "Operation Iron Vanguard"],
        "statuses": ["All"] + CASUALTY_STATUSES,
        "sectors": ["All"] + [f"Sector {s}" for s in REPORT_SECTORS],
    }
 
 
def _get_recent_reports() -> list[dict]:
    """
    # TODO Integration:
    # Source -> crud.get_recent_reports(limit=N) reading the future
    # Reports table, ordered by generated_time DESC. report_id will be
    # that table's primary key; generated_by will be Reports.requested_by,
    # populated from a future auth/session-identity system (none exists
    # yet — see the ROLE_* constants above).
    """
    return [
        {"report_id": "RPT-001", "report_type": "Casualty Summary", "name": "Casualty Summary — Sector Bravo", "generated_time": "09:42", "status": "Completed", "generated_by": ROLE_MED_COMMAND},
        {"report_id": "RPT-002", "report_type": "Facility Performance", "name": "Facility Performance — HMV", "generated_time": "08:57", "status": "Completed", "generated_by": ROLE_OPS_OFFICER},
        {"report_id": "RPT-003", "report_type": "Mission SITREP", "name": "Mission SITREP — 0800", "generated_time": "08:00", "status": "Completed", "generated_by": ROLE_SYSTEM},
        {"report_id": "RPT-004", "report_type": "Resource Utilization", "name": "Resource Utilization — 24h", "generated_time": "07:15", "status": "Pending", "generated_by": ROLE_DUTY_OFFICER},
        {"report_id": "RPT-005", "report_type": "Incident Timeline", "name": "Incident Timeline — Operation Shield Wall", "generated_time": "06:30", "status": "Failed", "generated_by": ROLE_OPS_OFFICER},
    ]
 
 
def _get_queued_reports() -> list[dict]:
    """
    # TODO Integration:
    # Source -> crud.get_report_generation_queue() reading the future
    # Reports table filtered to status IN ('Queued', 'Processing'),
    # ordered by queue position. Distinct from Recent Reports (completed/
    # failed generation) and from CSV export itself (backend only
    # supports CSV today — see the disabled Export button below).
    """
    return [
        {"report_id": "RPT-006", "report_type": "Resource Utilization", "name": "Resource Utilization — 24h", "generated_time": "07:15", "status": "Pending", "generated_by": ROLE_DUTY_OFFICER},
        {"report_id": "RPT-007", "report_type": "Facility Performance", "name": "Facility Performance — FDC", "generated_time": "07:40", "status": "Processing", "generated_by": ROLE_OPS_OFFICER},
    ]
 
 
def _get_archived_reports() -> list[dict]:
    """
    # TODO Integration:
    # Source -> crud.get_archived_reports(limit=N) reading the future
    # Reports table filtered to status = 'Archived' (or an is_archived
    # flag), ordered by archived_time DESC.
    """
    return [
        {"report_id": "RPT-008", "report_type": "Mission SITREP", "name": "Mission SITREP — Day 3", "generated_time": "05 Jul, 08:00", "status": "Archived", "generated_by": ROLE_SYSTEM},
        {"report_id": "RPT-009", "report_type": "Casualty Summary", "name": "Casualty Summary — Operation Iron Vanguard", "generated_time": "03 Jul, 18:20", "status": "Archived", "generated_by": ROLE_MED_COMMAND},
        {"report_id": "RPT-010", "report_type": "Treatment Outcomes", "name": "Treatment Outcomes — Weekly", "generated_time": "01 Jul, 09:10", "status": "Archived", "generated_by": ROLE_OPS_OFFICER},
    ]
 
 
def _get_report_stats() -> dict:
    """
    # TODO Integration:
    # Source -> a single crud.get_report_status_counts() query
    # (SELECT status, COUNT(*) ... GROUP BY status) over the future
    # Reports table, once it exists. Today this is computed client-side
    # over the three mock lists above only, purely for the stats strip.
    """
    all_reports = _get_recent_reports() + _get_queued_reports() + _get_archived_reports()
    completed = sum(1 for r in all_reports if r["status"] == "Completed")
    queued = sum(1 for r in all_reports if r["status"] in ("Queued", "Processing", "Pending"))
    archived = sum(1 for r in all_reports if r["status"] == "Archived")
    failed = sum(1 for r in all_reports if r["status"] == "Failed")
    return {"Completed": completed, "Queued": queued, "Archived": archived, "Failed": failed}
 
 
def _get_summary_stats() -> dict:
    """
    # TODO Integration:
    # Source -> aggregation over Casualty/Incident/Treatment rows for the
    # currently selected Report Builder filters (crud.get_casualties(),
    # crud.get_incidents(), crud.get_treatments(), all filterable by the
    # same fields exposed in the builder above, including Sector ->
    # Casualty.battle_sector / Incident.battle_sector).
    """
    return {
        "total_incidents": 46,
        "total_casualties": 1250,
        "recovered": 320,
        "returned_to_duty": 210,
        "avg_treatment_hours": 18.4,
        "period_label": "Last 7 days",
    }
 
 
def _get_table_preview_rows() -> list[dict]:
    """
    # TODO Integration:
    # Source -> crud.get_casualties(filters=...) joined against Facility
    # for facility_name, shaped to the Report Builder's active filters
    # (including Sector).
    """
    return [
        {"casualty_id": "CAS-004", "severity": "Mild", "facility": "RAP", "status": "Recovered", "arrival_time": "08:12"},
        {"casualty_id": "CAS-011", "severity": "Moderate", "facility": "ADS", "status": "Under Treatment", "arrival_time": "08:40"},
        {"casualty_id": "CAS-017", "severity": "Serious", "facility": "HMV", "status": "Under Treatment", "arrival_time": "09:32"},
        {"casualty_id": "CAS-022", "severity": "Critical", "facility": "FDC", "status": "Under Treatment", "arrival_time": "09:50"},
        {"casualty_id": "CAS-029", "severity": "Mild", "facility": "RAP", "status": "Returned To Duty", "arrival_time": "07:05"},
    ]
 
 
def _get_severity_breakdown() -> dict:
    """
    # TODO Integration:
    # Source -> crud.get_casualties(filters=...) grouped by severity,
    # COUNT(*), for the Report Builder's active date range/filters.
    """
    return {"Critical": 138, "Serious": 340, "Moderate": 452, "Mild": 320}
 
 
def _get_incident_distribution() -> dict:
    """
    # TODO Integration:
    # Source -> crud.get_incidents(filters=...) grouped by event_type,
    # COUNT(*), for the active date range.
    """
    return {
        "Mortar Attack": 12,
        "Artillery Strike": 9,
        "IED Explosion": 7,
        "Sniper Fire": 6,
        "Ambush": 5,
        "Landmine Blast": 4,
        "Convoy Attack": 3,
    }
 
 
def _get_facility_utilization_trend() -> dict:
    """
    # TODO Integration:
    # Source -> Treatments.treatment_start grouped by day and facility_id,
    # joined against Facility.capacity for a per-day occupancy_pct. This
    # is historical (day-bucketed), unlike Analytics' live hour-bucketed
    # trend — distinct query, same underlying tables.
    """
    days = [(date.today() - timedelta(days=d)).strftime("%d %b") for d in range(HISTORY_DAYS - 1, -1, -1)]
    return {
        "days": days,
        "series": {
            "RAP": [42, 45, 48, 50, 55, 58, 58],
            "ADS": [55, 58, 60, 62, 61, 60, 60],
            "HMV": [60, 61, 63, 65, 66, 63, 63],
            "FDC": [64, 65, 66, 68, 69, 68, 68],
        },
    }
 
 
def _get_treatment_duration_distribution() -> dict:
    """
    # TODO Integration:
    # Source -> Treatments.treatment_duration bucketed into ranges, for
    # completed treatments (treatment_end IS NOT NULL) in the active
    # date range.
    """
    return {
        "buckets": ["< 4h", "4-24h", "1-4d", "4-10d", "10-20d", "> 20d"],
        "counts": [180, 240, 210, 130, 60, 25],
    }
 
 
def _get_evacuation_flow_timeline() -> dict:
    """
    # TODO Integration:
    # Source -> Casualty.assigned_facility transitions over time, derived
    # from Treatment rows ordered by treatment_start per casualty_id:
    # each time a casualty's facility changes (RAP->ADS, ADS->HMV,
    # HMV->FDC), or their status becomes "Returned To Duty" out of FDC,
    # that's one flow event. Bucketed by day. No new schema needed — this
    # is a derived query over existing Treatments + Casualty.status, same
    # tables Facility Utilization Trend above already reads.
    """
    days = [(date.today() - timedelta(days=d)).strftime("%d %b") for d in range(HISTORY_DAYS - 1, -1, -1)]
    return {
        "days": days,
        "series": {
            "RAP → ADS": [8, 10, 9, 12, 11, 14, 13],
            "ADS → HMV": [5, 6, 7, 8, 7, 9, 9],
            "HMV → FDC": [3, 3, 4, 5, 4, 6, 5],
            "FDC → Returned To Duty": [1, 2, 2, 3, 3, 4, 4],
        },
    }
 
 
# --------------------------------------------------------------------------
# CHART LAYER (Plotly, styled to match Dashboard/Analytics)
# --------------------------------------------------------------------------
 
def _base_layout(figure: go.Figure) -> go.Figure:
    figure.update_layout(
        margin=dict(l=10, r=10, t=10, b=10),
        height=CHART_HEIGHT_PX,
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font_color=COLOR_TEXT_SECONDARY,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    )
    return figure
 
 
def _build_severity_chart(data: dict) -> go.Figure:
    labels = list(data.keys())
    values = list(data.values())
    colors = [SEVERITY_COLOR.get(label, COLOR_INFO) for label in labels]
    figure = go.Figure(go.Bar(x=labels, y=values, marker_color=colors, text=values, textposition="outside"))
    figure = _base_layout(figure)
    figure.update_yaxes(showgrid=True, gridcolor="rgba(255,255,255,0.06)")
    figure.update_xaxes(showgrid=False)
    return figure
 
 
def _build_incident_distribution_chart(data: dict) -> go.Figure:
    items = sorted(data.items(), key=lambda kv: kv[1])
    labels = [k for k, _ in items]
    values = [v for _, v in items]
    figure = go.Figure(go.Bar(
        x=values, y=labels, orientation="h",
        marker_color=COLOR_DANGER, text=values, textposition="outside",
    ))
    figure = _base_layout(figure)
    figure.update_xaxes(showgrid=True, gridcolor="rgba(255,255,255,0.06)")
    figure.update_yaxes(showgrid=False)
    return figure
 
 
def _build_facility_utilization_trend_chart(data: dict) -> go.Figure:
    palette = [COLOR_PRIMARY, COLOR_INFO, COLOR_WARNING, COLOR_DANGER]
    figure = go.Figure()
    for color, (facility, values) in zip(palette, data["series"].items()):
        figure.add_trace(go.Scatter(
            x=data["days"], y=values, name=facility,
            mode="lines+markers", line=dict(color=color, width=2),
        ))
    figure = _base_layout(figure)
    figure.update_yaxes(showgrid=True, gridcolor="rgba(255,255,255,0.06)", ticksuffix="%")
    figure.update_xaxes(showgrid=False)
    return figure
 
 
def _build_treatment_duration_chart(data: dict) -> go.Figure:
    figure = go.Figure(go.Bar(
        x=data["buckets"], y=data["counts"], marker_color=COLOR_INFO,
        text=data["counts"], textposition="outside",
    ))
    figure = _base_layout(figure)
    figure.update_yaxes(showgrid=True, gridcolor="rgba(255,255,255,0.06)")
    figure.update_xaxes(showgrid=False)
    return figure
 
 
def _build_evacuation_flow_timeline_chart(data: dict) -> go.Figure:
    palette = [COLOR_PRIMARY, COLOR_INFO, COLOR_WARNING, COLOR_DANGER]
    figure = go.Figure()
    for color, (stage, values) in zip(palette, data["series"].items()):
        figure.add_trace(go.Scatter(
            x=data["days"], y=values, name=stage,
            mode="lines+markers", line=dict(color=color, width=2),
        ))
    figure = _base_layout(figure)
    figure.update_yaxes(showgrid=True, gridcolor="rgba(255,255,255,0.06)")
    figure.update_xaxes(showgrid=False)
    return figure
 
 
# --------------------------------------------------------------------------
# SMALL SHARED MARKUP HELPERS
# --------------------------------------------------------------------------
 
def _template_badge_html(name: str) -> str:
    """Boxed badge used on Report Templates cards (e.g. 'CAS')."""
    code = TEMPLATE_BADGE.get(name, "GEN")
    color = TEMPLATE_BADGE_COLOR.get(name, COLOR_INFO)
    return (
        '<span style="display:inline-flex;align-items:center;justify-content:center;'
        'min-width:38px;height:24px;padding:0 6px;margin-right:10px;'
        f'border:1px solid {color};border-radius:4px;background:rgba(255,255,255,0.03);'
        f'font-size:0.72rem;font-weight:700;letter-spacing:0.04em;color:{color};'
        'font-family:monospace;vertical-align:middle;">'
        f'{code}</span>'
    )
 
 
def _type_tag_html(report_type: str) -> str:
    """Bracketed inline tag used on report list rows (e.g. '[CAS]')."""
    code = TEMPLATE_BADGE.get(report_type, "GEN")
    color = TEMPLATE_BADGE_COLOR.get(report_type, COLOR_INFO)
    return (
        f'<span style="font-family:monospace;font-weight:700;font-size:0.72rem;'
        f'color:{color};margin-right:8px;letter-spacing:0.02em;">[{code}]</span>'
    )
 
 
def _render_centered_placeholder(icon: str, title: str, caption: str) -> None:
    """Centered icon + title + caption, matching the placeholder pattern
    already used by Dashboard's Battlefield Map / Triage Chart panels."""
    st.write("")
    _, center, _ = st.columns([1, 2, 1])
    with center:
        st.markdown(f"# {icon}")
        st.markdown(f"### {title}")
        st.caption(caption)
    st.write("")
 
 
def _render_report_id_badge(report_id: str) -> str:
    return f'<span style="font-family:monospace;font-size:0.78rem;color:{COLOR_TEXT_SECONDARY};">{report_id}</span>'
 
 
# --------------------------------------------------------------------------
# RENDER LAYER
# --------------------------------------------------------------------------
 
def _render_classification_badge() -> None:
    st.markdown(
        '<div style="display:flex;align-items:center;gap:10px;margin-bottom:14px;">'
        '<span style="font-size:1.1rem;font-weight:700;color:var(--color-text-primary);">Reports</span>'
        f'<span class="medevac-status-badge" style="color:{COLOR_WARNING};">'
        '<span class="medevac-status-dot"></span>CLASSIFICATION: OPERATIONAL USE</span>'
        '</div>',
        unsafe_allow_html=True,
    )
 
 
def _render_kpi_row() -> None:
    cards = _get_report_kpis()
    columns = st.columns(len(cards))
    for column, card in zip(columns, cards):
        with column:
            metric_card(title=card["title"], value=card["value"], color=card["color"])
 
 
def _render_report_templates() -> None:
    templates = _get_report_templates()
    columns = st.columns(3)
    for i, template in enumerate(templates):
        with columns[i % 3]:
            with st.container(border=True):
                badge_html = _template_badge_html(template["name"])
                st.markdown(f'{badge_html}<strong>{template["name"]}</strong>', unsafe_allow_html=True)
                st.caption(template["description"])
                # TODO Integration: on click -> crud.create_report(template=...)
                # once report generation + the Reports table exist.
                clicked = secondary_button("Generate", key=f"reports_template_generate_{i}")
                if clicked:
                    st.session_state["reports_selected_template"] = template["name"]
                    st.session_state["reports_last_generated_by"] = _MOCK_CURRENT_USER
                    st.session_state["reports_last_generation_time"] = datetime.now().strftime("%H:%M")
                    st.session_state["reports_last_filters_applied"] = "No filters (template default)"
                    st.session_state["reports_has_generated"] = True
 
 
def _compute_filters_applied_label() -> str:
    filter_keys = {
        "Facility": "reports_filter_facility",
        "Severity": "reports_filter_severity",
        "Incident Type": "reports_filter_incident_type",
        "Sector": "reports_filter_sector",
        "Status": "reports_filter_status",
        "Operation": "reports_filter_operation",
    }
    applied = [
        f"{label}: {st.session_state[key]}"
        for label, key in filter_keys.items()
        if st.session_state.get(key, "All") != "All"
    ]
    return "; ".join(applied) if applied else "No filters applied"
 
 
def _render_report_builder() -> None:
    options = _get_filter_options()
 
    row1 = st.columns(2)
    with row1[0]:
        st.caption("Date Range")
        st.date_input(
            "Date Range",
            value=(date.today() - timedelta(days=HISTORY_DAYS - 1), date.today()),
            key="reports_filter_date_range",
            label_visibility="collapsed",
        )
    with row1[1]:
        st.caption("Operation")
        st.selectbox("Operation", options["operations"], key="reports_filter_operation", label_visibility="collapsed")
 
    row2 = st.columns(2)
    with row2[0]:
        st.caption("Facility")
        st.selectbox("Facility", options["facilities"], key="reports_filter_facility", label_visibility="collapsed")
    with row2[1]:
        st.caption("Sector")
        st.selectbox("Sector", options["sectors"], key="reports_filter_sector", label_visibility="collapsed")
 
    row3 = st.columns(2)
    with row3[0]:
        st.caption("Severity")
        st.selectbox("Severity", options["severities"], key="reports_filter_severity", label_visibility="collapsed")
    with row3[1]:
        st.caption("Incident Type")
        st.selectbox("Incident Type", options["incident_types"], key="reports_filter_incident_type", label_visibility="collapsed")
 
    row4 = st.columns(2)
    with row4[0]:
        st.caption("Status")
        st.selectbox("Status", options["statuses"], key="reports_filter_status", label_visibility="collapsed")
 
    st.write("")
    # TODO Integration: on click -> gather the six selectbox values above,
    # call crud.create_report(filters=...), then refresh the report tabs
    # and Report Preview from the returned report_id.
    generated = primary_button("Generate Report", key="reports_builder_generate")
    if generated:
        st.session_state["reports_selected_template"] = st.session_state.get("reports_selected_template", "Custom Report")
        st.session_state["reports_last_generated_by"] = _MOCK_CURRENT_USER
        st.session_state["reports_last_generation_time"] = datetime.now().strftime("%H:%M")
        st.session_state["reports_last_filters_applied"] = _compute_filters_applied_label()
        st.session_state["reports_has_generated"] = True
 
 
def _render_report_metadata_strip() -> None:
    top_fields = [
        ("Selected Template", st.session_state.get("reports_selected_template", "—")),
        ("Generated By", st.session_state.get("reports_last_generated_by", "—")),
        ("Generation Time", st.session_state.get("reports_last_generation_time", "—")),
    ]
    columns = st.columns(3)
    for column, (label, value) in zip(columns, top_fields):
        with column:
            st.caption(label)
            st.markdown(f"**{value}**")
 
    filters_value = st.session_state.get("reports_last_filters_applied", "No report generated yet")
    st.caption("Filters Applied")
    # Full-width row of its own, with explicit wrap styling, so a long
    # multi-filter string (e.g. several "Label: Value" pairs joined with
    # "; ") wraps at word boundaries instead of overflowing a narrow
    # column or breaking mid-word.
    st.markdown(
        '<div style="font-weight:600;color:var(--color-text-primary);'
        'white-space:normal;overflow-wrap:break-word;word-break:normal;'
        'line-height:1.5;">'
        f'{filters_value}</div>',
        unsafe_allow_html=True,
    )
    st.divider()
 
 
def _render_report_stats_strip() -> None:
    stats = _get_report_stats()
    stat_order = [
        ("Completed", "primary"),
        ("Queued", "warning"),
        ("Archived", "info"),
        ("Failed", "danger"),
    ]
    columns = st.columns(len(stat_order))
    for column, (label, accent_key) in zip(columns, stat_order):
        color = _ACCENT[accent_key]
        with column:
            st.markdown(
                f'<span style="font-size:0.72rem;color:{COLOR_TEXT_SECONDARY};'
                'text-transform:uppercase;letter-spacing:0.04em;">'
                f'{label}</span><br>'
                f'<span style="font-size:1.2rem;font-weight:700;color:{color};">{stats[label]}</span>',
                unsafe_allow_html=True,
            )
    st.write("")
 
 
def _render_empty_state(message: str) -> None:
    st.markdown(
        '<div style="text-align:center;padding:28px 12px;color:var(--color-text-secondary);">'
        '<div style="font-size:1.4rem;margin-bottom:6px;">—</div>'
        f'<div style="font-size:0.85rem;">{message}</div>'
        '</div>',
        unsafe_allow_html=True,
    )
 
 
def _render_report_table(reports: list[dict], time_label: str, key_prefix: str, empty_message: str) -> None:
    if not reports:
        _render_empty_state(empty_message)
        return
 
    col_widths = [1.1, 3.3, 1.7, 1.6, 1.3, 1.1]
    header = st.columns(col_widths)
    header[0].caption("ID")
    header[1].caption("Report Name")
    header[2].caption("Generated By")
    header[3].caption(time_label)
    header[4].caption("Status")
    header[5].caption("Export")
 
    for i, report in enumerate(reports):
        row = st.columns(col_widths)
        row[0].markdown(_render_report_id_badge(report["report_id"]), unsafe_allow_html=True)
        row[1].markdown(
            f'{_type_tag_html(report["report_type"])}<strong>{report["name"]}</strong>',
            unsafe_allow_html=True,
        )
        row[2].caption(report["generated_by"])
        row[3].caption(report["generated_time"])
        color = _ACCENT.get(REPORT_STATUS_COLOR.get(report["status"], "info"), COLOR_INFO)
        row[4].markdown(
            f'<span style="color:{color};font-weight:600;font-size:0.82rem;">{report["status"]}</span>',
            unsafe_allow_html=True,
        )
        with row[5]:
            # TODO Integration: enable once crud.export_report_csv(report_id)
            # exists backend-side (backend currently supports CSV export
            # only — no PDF/Excel/email, per spec). Placeholder only.
            st.button("⬇ CSV", key=f"{key_prefix}_csv_{i}", disabled=True, help="CSV export — backend integration pending")
        if i < len(reports) - 1:
            st.divider()
 
 
def _render_reports_section() -> None:
    _render_report_stats_strip()
 
    recent_tab, queued_tab, archived_tab = st.tabs(["Recent Reports", "Queued Reports", "Archived Reports"])
    with recent_tab:
        _render_report_table(
            _get_recent_reports(), time_label="Generated", key_prefix="reports_recent",
            empty_message="No reports generated yet. Use Report Builder or a template above to generate one.",
        )
    with queued_tab:
        _render_report_table(
            _get_queued_reports(), time_label="Queued", key_prefix="reports_queue",
            empty_message="No reports currently in the generation queue.",
        )
    with archived_tab:
        _render_report_table(
            _get_archived_reports(), time_label="Archived", key_prefix="reports_archived",
            empty_message="No archived reports yet.",
        )
 
 
def _render_preview_summary_tab() -> None:
    stats = _get_summary_stats()
    st.caption(stats["period_label"])
    cards = [
        {"title": "Total Incidents", "value": stats["total_incidents"], "color": "danger"},
        {"title": "Total Casualties", "value": stats["total_casualties"], "color": "info"},
        {"title": "Recovered", "value": stats["recovered"], "color": "primary"},
        {"title": "Returned To Duty", "value": stats["returned_to_duty"], "color": "primary"},
        {"title": "Avg Treatment Time", "value": f"{stats['avg_treatment_hours']}h", "color": "warning"},
    ]
    columns = st.columns(len(cards))
    for column, card in zip(columns, cards):
        with column:
            metric_card(title=card["title"], value=card["value"], color=card["color"])
 
 
def _render_preview_tables_tab() -> None:
    rows = _get_table_preview_rows()
    st.dataframe(
        rows,
        use_container_width=True,
        hide_index=True,
        column_config={
            "casualty_id": "Casualty ID",
            "severity": "Severity",
            "facility": "Facility",
            "status": "Status",
            "arrival_time": "Arrival Time",
        },
    )
    st.caption("Preview limited to 5 rows. Full table ships with CSV export once generation is wired.")
 
 
def _render_preview_charts_tab() -> None:
    left, right = st.columns(2)
    with left:
        st.caption("Casualties by Severity")
        st.plotly_chart(_build_severity_chart(_get_severity_breakdown()), use_container_width=True)
    with right:
        st.caption("Incident Distribution")
        st.plotly_chart(_build_incident_distribution_chart(_get_incident_distribution()), use_container_width=True)
 
    st.caption("Facility Utilization Trend")
    st.plotly_chart(_build_facility_utilization_trend_chart(_get_facility_utilization_trend()), use_container_width=True)
 
    left2, right2 = st.columns(2)
    with left2:
        st.caption("Treatment Duration Distribution")
        st.plotly_chart(_build_treatment_duration_chart(_get_treatment_duration_distribution()), use_container_width=True)
    with right2:
        st.caption("Evacuation Flow Timeline")
        st.plotly_chart(_build_evacuation_flow_timeline_chart(_get_evacuation_flow_timeline()), use_container_width=True)
 
 
def _render_report_preview() -> None:
    if not st.session_state.get("reports_has_generated"):
        _render_centered_placeholder(
            icon="▣",
            title="No Report Selected",
            caption="Select a template or generate a report to view historical summaries and visualizations.",
        )
        return
 
    _render_report_metadata_strip()
    summary_tab, tables_tab, charts_tab = st.tabs(["Summary", "Tables", "Charts"])
    with summary_tab:
        _render_preview_summary_tab()
    with tables_tab:
        _render_preview_tables_tab()
    with charts_tab:
        _render_preview_charts_tab()
 
 
def render() -> None:
    """Render the Reports page: classification badge, KPIs, templates,
    builder, report tabs, and preview."""
    _render_classification_badge()
 
    _render_kpi_row()
 
    st.markdown("<div style='height:18px;'></div>", unsafe_allow_html=True)
 
    with panel("Report Templates"):
        _render_report_templates()
 
    builder_col, recent_col = st.columns([2, 3])
 
    with builder_col:
        with panel("Report Builder"):
            _render_report_builder()
 
    with recent_col:
        with panel("Reports"):
            _render_reports_section()
 
    with panel("Report Preview"):
        _render_report_preview()
 